# ATSC 409 Assignment 3 Question 1

In [ ]:
import numpy as np

In [20]:
##### Solve the original matrix.
A = np.array([[-1/28e12 - 0.05, 1/25e13,        0],
              [0,               1/10e14,        -1/72e10 - 0.15],
              [1/28e12,         -7/5e14 - 0.05, 1/72e10 + 0.1]]) 
b = np.array([-1000, 0, -2000])
x = np.linalg.solve(A, b)
print(x)

[  2.00000000e+04   4.00000000e+04   2.66666667e-10]


In [19]:
##### Solve the matrix with L3 = 0.
A2 = np.array([[-1/28e12, 1/25e13, 0],
               [0,        1/10e14, -1/72e10 - 0.1],
               [1/28e12,  -7/5e14, 1/72e10 + 0.1]]) 
b2 = np.array([-1000, 0, -2000])
x2 = np.linalg.solve(A2, b2)
print(x2)

[  6.53333333e+16   3.33333333e+17   3.33333333e+03]


In [18]:
##### Solve the matrix with L3 = 0 and P1 = P2 = 0.
A3 = np.array([[-1/28e12, 1/25e13, 0],
               [0,        1/10e14, -1/72e10 - 0.1],
               [1/28e12,  -7/5e14, 1/72e10 + 0.1]]) 
b3 = np.array([0, 0, 0])
x3 = np.linalg.solve(A3, b3)
print(x3)

[-0. -0. -0.]


#ATSC 409 Assignment 3 Question 2

In [ ]:
import numpy as np
import scipy.stats as sps

In [10]:
##### Write a function that creates the differential system matrix of size N+1
##### x N+1 given N.
def dir(N):
    m = np.zeros((N+1, N+1))
    m[0, 0] = m[N, N] = 1
    for i in range(1,N):
        m[i, i-1] = m[i, i+1] = 1
        m[i, i] = -2
    return m
dir(10)

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1., -2.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1., -2.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1., -2.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1., -2.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1., -2.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1., -2.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1., -2.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1., -2.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1., -2.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]])

In [11]:
##### Compute the condition number for the differential system matrix for 
##### several values of N between 5 and 50.
K = np.ndarray((46,), float)
for i in range(5,51):
    K[i-5] = np.linalg.cond(dir(i))
print(K)

[   10.99460032    15.23311899    20.33652615    26.28708642    33.07381141
    40.68975498    49.13030204    58.39225245    68.47331059    79.37178441
    91.08639877   103.6161745    116.9603475    131.11831298   146.08958623
   161.87377438   178.47055573   195.87966446   214.10087905   233.13401347
   252.97891039   273.63543586   295.10347518   317.38292953   340.47371337
   364.37575226   389.08898114   414.61334289   440.94878717   468.09526945
   496.05275018   524.82119413   554.40056982   584.79084902   615.99200636
   648.00401895   680.82686612   714.46052914   748.904991     784.16023621
   820.22625064   857.1030214    894.79053664   933.28878553   972.59775809
  1012.71744515]


In [13]:
##### Take the N-1 x N-1 submatrix of dir(N) and compare the condition number
##### for the new matrix to the condition number for the original matrix.
def dire(N):
    m = np.zeros((N-1, N-1))
    for i in range(0,N-1):
        m[i, i] = -2
    for i in range(1,N-1):
        m[i, i-1] = m[i-1, i] = 1
    return m
dire(10)

array([[-2.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1., -2.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1., -2.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1., -2.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1., -2.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1., -2.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1., -2.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1., -2.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1., -2.]])

In [12]:
C = np.ndarray((46,), float)
for i in range(5,51):
    C[i-5] = np.linalg.cond(dire(i))
print(C)

[    9.47213595    13.92820323    19.19566936    25.27414237    32.16343748
    39.86345819    48.37415008    57.69548054    67.82742907    78.76998224
    90.52313097   103.08686892   116.46119158   130.64609564   145.64157867
   161.4476388    178.06427461   195.491485     213.7292691    232.77762622
   252.63655579   273.30605738   294.7861306    317.07677515   340.17799079
   364.0897773    388.81213449   414.34506223   440.68856038   467.84262884
   495.8072675    524.5824763    554.16825515   584.564604     615.77152279
   647.78901148   680.61707002   714.25569838   748.70489653   783.96466444
   820.03500208   856.91590943   894.60738648   933.10943319   972.42204956
  1012.54523556]


In [14]:
##### Is the difference between the condition numbers significant?
abs(C-K)

array([ 1.52246436,  1.30491576,  1.14085679,  1.01294405,  0.91037393,
        0.82629679,  0.75615196,  0.69677191,  0.64588152,  0.60180217,
        0.5632678 ,  0.52930558,  0.49915592,  0.47221734,  0.44800757,
        0.42613558,  0.40628111,  0.38817945,  0.37160995,  0.35638725,
        0.34235459,  0.32937849,  0.31734458,  0.30615438,  0.29572258,
        0.28597496,  0.27684664,  0.26828065,  0.26022678,  0.25264061,
        0.24548268,  0.23871784,  0.23231468,  0.22624503,  0.22048357,
        0.21500747,  0.2097961 ,  0.20483076,  0.20009447,  0.19557177,
        0.19124856,  0.18711196,  0.18315016,  0.17935234,  0.17570854,
        0.17220958])

In [15]:
##### Perform a one-sample t-test on the differences.
sps.ttest_1samp(abs(C-K), 0)

(9.3646236705173589, 3.9012462234016944e-12)

Based on the matrices above, it is obvious that the condition number C or K increases as the size of the matrix N increases. According to the one-sample t-test, there is no significant difference between the condition numbers of the A1 matrices (original w/ size N+1 x N+1) and the condition numbers of the A2 matrices (modified w/ size N-1 x N-1).